/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(19))
    }
    jvmToolchain(19)
}
java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(19))
}
plugins {
    `java-library`
    `maven-publish`
    kotlin("jvm") version "1.9.0"
    id("me.champeau.jmh") version "0.6.6"
}
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = "19" // Use the same version as Java
}
tasks.withType<JavaCompile>().configureEach {
    sourceCompatibility = "19" // Match your desired Java version
    targetCompatibility = "19"
    options.encoding = "UTF-8"
}


java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(19)) // Match Kotlin's version
}


repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.jetbrains.kotlin.kotlin.stdlib.jdk8)
    testImplementation(libs.org.jetbrains.kotlin.kotlin.test.junit5)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    implementation("commons-io:commons-io:2.7")
    implementation("org.openjdk.jmh:jmh-core:0.9")
    implementation("org.openjdk.jmh:jmh-generator-annprocess:0.9")
    implementation("org.openjdk.jmh:jmh-generator-bytecode:0.9")
}

group = "org.kotlinprac"
version = "1.0-SNAPSHOT"
description = "consoleApp"
java.sourceCompatibility = JavaVersion.VERSION_1_8


tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
apply(plugin = "me.champeau.jmh")
